### ISSUE TITLE
VCLua Canvas

### ISSUE THREAD

**Issue by user357** [hipBali/vclua#14]
How to use canvas ?

I want to use canvas for drawing graphs.
-------------------------------------------
VCL = require "vcl.core"
VCL.Application():Initialize()

local mainFrm = VCL.Form(nil,'mainForm')

local canvas = VCL.canas(mainPanel,'canvas')

mainFrm._ = {
	caption='VCLua Button example',
	width=640,
	height=480,
	position="poScreenCenter",
}

canvas._ =  {
	width=100,
	height=100,
}

This not working !

Need more examples in [[vclua](https://github.com/hipBali/vclua/tree/initial-v1)/examples](https://github.com/hipBali/vclua/tree/initial-v1/examples).

**Comment by hipBali** [comment]
Some components have a canvas but some have'nt.

Here is a small sample of the usage:

```
VCL = require "vcl.core"
VCL.Application():Initialize()

local mainFrm = VCL.Form(nil,'mainForm',{
	Caption='VCLua Canvas example',
	Width=640,
	Height=480,
	Position="poScreenCenter",
})

local function onPaint(sender)
	local Canvas = sender.Canvas
	Canvas.Brush.Color = 0x22DD44
	Canvas.Brush.Style = 'bsSolid'
	Canvas:Rectangle(100,50,160,110)
end

mainFrm.OnPaint = onPaint

mainFrm:ShowModal()
```

more info at : https://wiki.freepascal.org/Graphics_-_Working_with_TCanvas

**Comment by user357** [comment]
> Some components have a canvas but some have'nt.
> 
> Here is a small sample of the usage:
> 
> ```
> VCL = require "vcl.core"
> VCL.Application():Initialize()
> 
> local mainFrm = VCL.Form(nil,'mainForm',{
> 	Caption='VCLua Canvas example',
> 	Width=640,
> 	Height=480,
> 	Position="poScreenCenter",
> })
> 
> local function onPaint(sender)
> 	local Canvas = sender.Canvas
> 	Canvas.Brush.Color = 0x22DD44
> 	Canvas.Brush.Style = 'bsSolid'
> 	Canvas:Rectangle(100,50,160,110)
> end
> 
> mainFrm.OnPaint = onPaint
> 
> mainFrm:ShowModal()
> ```
> 
> more info at : https://wiki.freepascal.org/Graphics_-_Working_with_TCanvas

Thank you)
