### ISSUE TITLE
About ANSI version

### ISSUE THREAD

**Issue by roman-orekhov** [hipBali/vclua#15]
Thank you for your great library!

Would you mind providing binaries for ANSI version of x86_64_win_lua53 and x86_64_win_lua54 in addition to utf8 ones I see in sourceforge? Or an instruction on how to build one?

For version 0.5.0 there is a [fork](https://github.com/swerg/QVCLua-0.5.0) created mainly for string encoding reasons since the base app is ANSI only and there's a need to display strings provided by that app inside its plugins. But this fork isn't updated for newer controls.

The problem is, in example like [this](https://github.com/hipBali/vclua/blob/initial-v1/examples/input.lua), ANSI encoded strings for e.g. `Memo1` lines, show up as "????", and `Memo1.lines:GetText()` produces typical UTF8-read-as-ANSI garbage when one inputs ANSI strings in Memo1 control.

**Comment by hipBali** [comment]
Hi Roman,
please read this article:  [Unicode Support in Lazarus](https://wiki.freepascal.org/Unicode_Support_in_Lazarus).
Maybe adding WinCPToUTF8 function to library will be enough?

More intresting question is what is the problem with the building instructions. because if it's incomprehensible, i should change it.
You don't need to generate the pascal source except if you want add additional components. Simple define the target lua version as described and run lazbuild executable.

j.

**Comment by roman-orekhov** [comment]
> please read this article: [Unicode Support in Lazarus](https://wiki.freepascal.org/Unicode_Support_in_Lazarus).
> Maybe adding WinCPToUTF8 function to library will be enough?

Yeah, I've read that and from the [article](https://wiki.freepascal.org/Lazarus_with_FPC3.0_without_UTF-8_mode#Problem_applications_with_ACP_strings_and_LCL_controls) it links to I see that for situation where most of the app is not UTF8 the provided option `-dDisableUTF8RTL` doesn't take care of string conversion to/from `LCL` unfortunately. The 0.5.0 fork does it seamlessly to Lua users, so the users had accumulated 100s of Lua scripts throughout the years already. Even if the library would export `WinCPToUTF8` and `UTF8ToWinCP` it's unlikely users would rewrite their scripts to convert strings themselves.

So I thought there could have been a switch inside the generator which would enable automatic WinCP<->UTF8 conversion for all controls at once. Or perhaps not a switch but a check if `-dDisableUTF8RTL` is provided with insertion of automatic conversions.

The instructions you provided are great to build _default_ assets. It's just encoding isn't mentioned at all. And an example of adding custom control would be useful (but that's off topic and probably would only be useful to those new to Free Pascal).

**Comment by hipBali** [comment]
Ok. 
The source generator uses definitions from module `src_generator/lua_make/classdef.lua`, where all the string related conversions must be updated to handle the codepage conversion.
The property handler module `LuaProperties.pas` must be updated as well.
Any other suggestions?

**Comment by hipBali** [comment]
[UTF8 conversion test](https://sourceforge.net/projects/vclua/files/vclua-v0.9.2/test_version/)
hi, please check this library (lua5.4) and the example code.
j.

**Comment by roman-orekhov** [comment]
Hi!
Using official lua54.exe with lua54.dll from the app I can only see 1251 characters with `VCL.setCPUTF8(true)` set in `test_cputf8.lua`

If I add `VCL.setCPUTF8(true)` in [input.lua](https://github.com/hipBali/vclua/blob/initial-v1/examples/input.lua), change text to 1251 codepage and run example from the app, it correctly displays the text. But if I edit the text and save it using `Memo1.lines:GetText()`, new text is saved as UTF8-read-as-ANSI garbage irrespective of `VCL.setCPUTF8(true)` or `VCL.setCPUTF8(false)`. Old text is saved as "???" with `false` and as UTF8-read-as-ANSI with `true`.

So with `VCL.setCPUTF8(false)` I get previous behavior.

Didn't you add conversions to getter functions?

**Comment by hipBali** [comment]
HI!
The getter/setter functions are managed by the source generator and the input/output is depending on the variable type. i just added the pchar output type to converter at classdef.lua. Please check the compiled code again.

**Comment by roman-orekhov** [comment]
Bingo, thank you!
Now the tests described above pass: in Memo I can see, edit and receive back correct string in CP1251, and 
ShowMessage also works.

> the input/output is depending on the variable type. i just added the pchar output type

So the GetText method returns a string (in Lua terms) and it's converted correctly now, but were there a method to get underlying table of strings (in Lua terms) one would get table of UTF8-encoded strings still?

Also why is `VCL.setCPUTF8(true)` needed to be set to true, not false? I think naming is misleading e.g. the call might be read as telling to VCL that "my program is using UTF8" while it works exactly when it's not using UTF8.

**Comment by hipBali** [comment]
The codepage conversion switch maybe should be renamed to setCPWIN...

> So the GetText method returns a string (in Lua terms) and it's converted correctly now, but were there a method to get underlying table of strings (in Lua terms) one would get table of UTF8-encoded strings still?

You must use the switch to turn on/off the automatic conversion. Every getter function called from the lua side receives converted or unconverted result: 
`if (is_vclua_utf8_conv) then
     lua_pushstring(L,pchar(UTF8ToWinCP(str)))
  else
    lua_pushstring(L,pchar(str));`

**Comment by roman-orekhov** [comment]
> The codepage conversion switch maybe should be renamed to setCPWIN

I would support `setCPWin` (with casing as in `UTF8ToWinCP` function) or `setWinCP`

**Comment by hipBali** [comment]
Done.
the next release will contain the changes. [v0.9.2-rc1](https://github.com/hipBali/vclua/tree/development-0.9.2)
j.

**Comment by roman-orekhov** [comment]
Upon further testing something isn't working. In the [menu](https://github.com/hipBali/vclua/blob/initial-v1/examples/menu.lua#L56) example I changed some captions to these:
```Lua
	{name="fileSave", caption="Сохранить проект", shortcut="Ctrl+S", imageIndex=2, onexecute=menuClick },
	{name="fileSaveAs", caption="С&охранить проект как...", imageIndex=3, onexecute=menuClick },		
```
And the items are "???" no matter the setting.

Also `setupImages` refers to `vcl` instead of `VCL`

**Comment by hipBali** [comment]
The test binary was updated. Im forgot update the handling of the TTranslateString and TWideString types in luaproperties module.
The vcl renference should be VCL, so thank you.
j.

**Comment by roman-orekhov** [comment]
> Would you mind providing binaries for ANSI version of x86_64_win_lua53 and x86_64_win_lua54 in addition to utf8 ones I see in sourceforge?

Would a 5.3 0.9.2 version be released as well?

**Comment by hipBali** [comment]
lua5.3 version is added to the binaries
