### ISSUE TITLE
ToolBar can't add ToolButtons

### ISSUE THREAD

**Issue by roman-orekhov** [hipBali/vclua#17]
Trying to follow [this](https://wiki.freepascal.org/TToolBar) example.

```Lua
VCL = require "vcl.core"
VCL.Application():Initialize()
dAlert = VCL.Form(nil,'dAlert')
tb = VCL.ToolBar(dAlert, "tb", {Align="alBottom", ShowCaptions=true})
bSave = VCL.ToolButton(tb,'b1',{Caption="aaaaa",AutoSize=true, Style="tbsButton", Left = tb.Left})
bCancel=VCL.ToolButton(tb,'b2',{Caption="bbbbb",AutoSize=true, Style="tbsButton", Left = tb.Left})
dAlert:ShowModal()
```

No toolbuttons are added to the toolbar. But other things like a `Button` are added ok.

**Comment by hipBali** [comment]
This is a bug in the lua_make/config.lua script.
The noparent flag must be removed from ToolButton class.
```
{ unit = "ToolBar", ref = "ComCtrls, Controls, ImgList, LuaImageList", canvas=true,
		classes = {
			{ name = "ToolButton", src = "TToolButton", noparent=true,},
			{ name = "ToolBar", src = "TToolBar" },
		}
	},
```

**Comment by hipBali** [comment]
Version 0.9.2 is out, binaries are updated, toolbar example added.
j.

**Comment by roman-orekhov** [comment]
> Version 0.9.2 is out, binaries are updated, toolbar example added. j.

Is it retracted? [This](https://sourceforge.net/projects/vclua/files/vclua-v0.9.2/) folder has no files.

PS: here, not to spam with issues: wrong copyright year in lib examples and vt-form sources, missing class reference for GroupBox (I even thought it wasn't implemented), and that class reference wasn't regenerated for 0.9.2

**Comment by hipBali** [comment]
Sorry just staged for a while.

> wrong copyright year in lib examples and vt-form sources, missing class reference for GroupBox (I even thought it wasn't implemented), and that class reference wasn't regenerated for 0.9.2
Could you explain more? 
GroupBox is implemented and working for me...
Thanks for copyright warning, i hope that vt-form can be useful tool, but it's have lots of issues...
Also lua-lar is available for lua5.4, just check it.
j

**Comment by roman-orekhov** [comment]
GroupBox is just missing from the docs since the docs (class reference) were not updated to reflect later changes. I haven't tested the control yet.

**Comment by hipBali** [comment]
Thank you!
