### ISSUE TITLE
Setting AnchorSide* without Align causes UNKNOWN EXCEPTION at address 00007FF91267CF19

### ISSUE THREAD

**Issue by roman-orekhov** [hipBali/vclua#18]
```Lua
VCL = require "vcl.core"
VCL.Application():Initialize()
dAlert = VCL.Form(nil,'dAlert', {Position = "podesktopcenter"
, BorderStyle = "bsSizeable", BorderWidth = 2, ShowInTaskbar="stAlways"
, Height = 460, Width = 774
, Font = {Size = 10}
})
bSave = VCL.Button(dAlert,'b1',{Caption="Save", Align="alLeft"})
bCancel=VCL.Button(dAlert,'b2',{Caption="Cancel", AnchorSideLeft={Control=bSave,Side="asrRight"}})
dAlert:ShowModal()   -- here: UNKNOWN EXCEPTION at address 00007FF91267CF19
```

Adding `, Anchors='[akTop, akLeft, akRight, akBottom]'` to either/both buttons crashes the same.

Am I doing something silly to any LCL programmer?

**Comment by hipBali** [comment]
[TAnchorSide](https://lazarus-ccr.sourceforge.io/docs/lcl/controls/tanchorside.html)  property side has no anchorable side named 'asrRight'.  (Just follow the links)
But the library should'nt cause error like this, the setProperty method must handle these errors...

**Comment by roman-orekhov** [comment]
Ah, really, those constants are defined [elsewhere](https://lazarus-ccr.sourceforge.io/docs/lcl/controls/asrright.html). That's why automatic conversion wouldn't handle them.

BTW why does `Control` have `AnchorAsAlign` and other `Anchor*` methods but its descendants (i.e. all other controls, including Button) don't have such methods and so have to be anchored by other means (e.g. like I tried in the code above)?

Feel free to close this anytime.
