### ISSUE TITLE
Can't create GridColumns

### ISSUE THREAD

**Issue by roman-orekhov** [hipBali/vclua#19]
```Lua
VCL = require "vcl.core"
VCL.Application():Initialize()
mainForm = VCL.Form(nil, "vf")
grid = VCL.StringGrid(mainForm,"g")
print(-1)
columns = VCL.GridColumns(grid)
print(0)
```

```
-1
UNKNOWN EXCEPTION at address 00007FFB3668CF19
```

(Lua 5.3)

Same happens with `VCL.GridColumns()` and `VCL.GridColumns(mainForm)`

**Comment by roman-orekhov** [comment]
`GridColumns` doesn't have any properties, so it's even impossible to access already created `GridColumns` via e.g. `grid.Columns[0]`

**Comment by hipBali** [comment]
```
VCL = require "vcl.core"
VCL.Application():Initialize()
mainForm = VCL.Form(nil, "vf")
grid = VCL.StringGrid(mainForm,"g")
col = grid.columns:Add()
print(col, col.classname)
```

**Comment by hipBali** [comment]
[Columns](https://lazarus-ccr.sourceforge.io/docs/lcl/grids/tgridcolumns.html
)
[One columns](https://lazarus-ccr.sourceforge.io/docs/lcl/grids/tgridcolumn.html)

**Comment by roman-orekhov** [comment]
As a temporary solution that's ok, thank you.
As longterm -- why export `GridColumns` function then if it's unusable? And it would still impossible to get already created column from `grid.columns` by index, only by title. Noone would be willing to maintain results of `grid.columns:Add()` in a table themselves.

**Comment by hipBali** [comment]
CellsGet and CellsSet methods added to test release 2.
```
grid.rowcount = 3
grid:CellsSet(2,2,"Hello")
print(grid:CellsGet(2,2))
```

**Comment by roman-orekhov** [comment]
Uploaded version contains `SetCells` and `GetCells` which are IMO better names than `CellsSet` and `CellsGet`. Forks used to have `SetCell` and `GetCell`.
