### ISSUE TITLE
Setting TColor from another TColor or double is broken

### ISSUE THREAD

**Issue by roman-orekhov** [hipBali/vclua#20]
```Lua
grid = VCL.StringGrid(mainForm,"grid")
print(grid.Color)
grid._={ FixedColor = grid.Color}
```

```
-2147483643.0
UNKNOWN EXCEPTION at address 00007FFB3668CF19
```

`grid._={ FixedColor = -2147483643.0 }` crashes the same.

Using `-2147483643` or `math.tointeger(grid.Color)` works.

**Comment by hipBali** [comment]
TColor type is integer, but you can use constant color names too. [Colors](https://wiki.freepascal.org/Colors). No other variable types are supported.
```
obj.color = "clMoneyGreen"
cmp.color = 0x00AABBCC
```
May i close this topic?

**Comment by roman-orekhov** [comment]
> TColor type is integer

Why is it read as float then?

```Lua
> math.type(mainForm.Color)
float
```

> May i close this topic?

As long as statements like `grid.FixedColor = grid.Color` crash anyone would consider it a bug. I'd rather fix it than document a workaround...

**Comment by hipBali** [comment]
Sorry, i just forgot the important info for you, The property getter was wrong for the tkInteger type. solved.

**Comment by roman-orekhov** [comment]
Version from #19 indeed solves the issue, thanks!
